#import "template.typ": code-block, appendix, begin-appendices, template, title-page

#show: template

#title-page(
  title: "Assignment 4: Valet",
  course: "RBE 550 — Motion Planning",
  author: "Liam Jennings",
  date: "April 2026",
)

#outline()
#pagebreak()

== Introduction
This project implements a motion planning simulator for four vehicle types: a holonomic point robot, a differential drive, an Ackermann car, and an Ackermann car towing a trailer. Each vehicle navigates a randomly generated obstacle field from a fixed start pose to a goal pose, eventually resulting in a kinematically correct path between them.

The planner uses a python implementation of the Hybrid A\* search algorithm, exploring
// , a variant of A\* that searches over a continuous $(x, y, theta)$ state space while using a discretised grid for duplicate detection. 
the environment by generating circular arc motion primitives and verifying that they do not collide with any obstacles. When within a set range of the goal, the planner occasionally attempts to plan a direct path while exploring nodes. If this path is verified to be collision free, the planner reconstructs the overall path by tracing its steps back to the start pose. This path is then post-processed by probabilistic shortcutting and then resampled to a uniform velocity for smooth playback. 

Collision detection is built on #link("https://shapely.readthedocs.io/en/stable/")[shapely] polygon geometry. Shapely is slow for repeated small queries, so a broad-phase occupancy-grid filter and a pre-rotated heading cache were implemented to keep query cost low. 

See @appendix:setup and @appendix:deps for initial installation instructions and a description of notable external dependencies.
#figure(
    image("media/photos/trailer_sim.png", width: 70%),
    caption: [Trailer path animation mid-playback. The traced path follows the center of the rear axle for the Ackermann vehicles, and the geometric center for differential drive and point robots. Blue dots mark the $(x, y)$ position of every state expanded during the planning phase.]
)

== Development Approach

Two approaches shaped how the project was built:

- *Incremental development:* Begin with a working holonomic point robot as a clean baseline for isolating planner bugs, then add each vehicle type in order of complexity. Optimisation was largely deferred until the planner was correct, and performance changes were driven by profiling data. This was a tradeoff between iteration speed and correctness.
- *Experimentation:* The project served as a testbed for Python's type system (`typing.Protocol`, generics) to keep vehicle types interchangeable without inheritance — an approach inspired by Rust traits. 

  The report similarly served as an exercise in Typst and technical writing. It is deliberately excessive, because I found it fun to make it so.

Shapely was used for collision detection from the start as a correct-if-slow reference implementation. Performance work was driven by `cProfile` and `snakeviz` profiling, with two targeted optimisations applied once bottlenecks were confirmed — covered in @fig:collision_opt.

== AI/LLM Usage Disclosure

This project was developed with assistance from LLM tools, primarily #link("https://claude.com/product/overview")[Claude]. Usage included acting as a partner for pair programming and assisting with research. 

The figure-generation scripts (see `valet/report/media/scripts`) are an exception: these were almost entirely written by the LLM, with manual tuning applied after.

#pagebreak()
= Approach


== Obstacle Environment Implementation

#figure(
    image("media/photos/obstacle_env.png",width: 80%),
    caption: [Obstacles generated given a 10% occupation requirement. Captured while driving the car in manual mode.]
)

The environment consists of a fixed-size 2D grid with randomly placed axis-aligned obstacles, a fixed start and goal at opposite corners, and a printable RNG seed for reproducibility. Obstacles are stored as both a NumPy boolean grid for fast broad-phase rejection and a Shapely `STRtree` #footnote[A spatial index structure for fast nearest-neighbour queries, in the same vein as an Octree] for exact intersection tests.

Obstacles are generated by randomly placing tetrominoes throughout the grid until a set proportion of the grid is occupied by obstacles. The standard proportion is 10%. The vehicles (green rectangle) start in the top left, and attempts to navigate to the goal pose (yellow rectangle) in the bottom right. The starting and ending positions are always cleared of obstacles prior to simulation start.

#figure(
    grid(
        columns: 2,
        gutter: 1em,
        image("media/photos/bot_goals/goal_pose_point.png"),
        image("media/photos/bot_goals/goal_pose_diff.png"),
        image("media/photos/bot_goals/goal_pose_car.png"),
        image("media/photos/bot_goals/goal_pose_trailer.png"),
    ),
    caption: [Goal poses for each vehicle type: point robot (top left), differential drive (top right), Ackermann car (bottom left), trailer (bottom right).]
)

=== Car Goal Offset

The car's goal pose uses a non-standard offset from the grid edge to ensure the parallel parking maneuver is both reachable and preserved. The tuning process is detailed in @appendix:car-offset.


== Collision Detection
// Demonstrate your collision checker implementation with annotated diagrams depicting overlap
// checks with a vehicle and obstacle region. Submit these diagrams individually, but also include
// them in your report.

The collision detector is required to handle two types of geometry: rotated rectangular footprints (the robot, car, truck, and trailer footprints) and line segments (the hitch bar connecting truck to trailer). Line segments can be cheaply checked via raycasting, while rectangular geometry is filtered through checks in order of increasing cost, exiting as soon as any check proves or disproves a vehicle's state will result in a collision. 

The first two checks use the axis-aligned bounding box: checking to see if it lies within the bounds of the environment, then checking if any of the cells covered by the box contain obstacles: 
#let validator = code-block()[
  ```
  function IS_VALID_STATE(geometries):
      for each geometry in geometries:
          if geometry is a line segment:
              if any endpoint lies outside the environment boundary:
                  return false
              if the segment intersects an obstacle:
                  return false
          else: // Geometry is a rotated rectangle
              compute translated axis-aligned bounding box
              if bounding box lies outside the environment boundary:
                  return false
              if no obstacle can possibly overlap the bounding box:
                  continue  // broad-phase rejection
              compute translated geometry
              if geometry intersects any obstacle:
                  return false
      return true
  ```
]

#figure(validator, caption: [Pseudocode describing state validation process.])

The most accurate collision check uses shapely's built-in geometry predicates, matching the initial design. Obstacles are stored as shapely `STRtree` of `box` polygons, allowing for easy exact intersection tests with the rotated polygons representing the vehicles. 

However, Shapely is designed for general topological geometry analysis and is not inherently optimised for repeated per-frame queries against a fixed obstacle set. Profiling with cProfile showed collision checking dominating overall runtime, therefore requiring the additional filter checks mentioned before, and further optimization via caching pre-rotated geometry. 

Their combined effect reduced total runtime significantly and brought the proportion occupied by collision checking roughly in line with primitive generation. The breakdown of the overall simulator runtime can be seen in @fig:icicle, and quantified results of the optimization can be seen in @fig:collision_opt.

#figure( 
    image("media/photos/icicle.svg", width: 115%),
    caption: [`snakeviz` Icicle plot of a profiled trailer simulation after optimisation. Time is now split roughly equally between primitive generation (propagate, 10.6 s) and collision checking (validate_path, 10.3 s), with is_valid_state accounting for 7.2 s of the collision budget.]
) <fig:icicle>

The subsections below describe each component in turn: the heading cache that eliminates per-query rotation cost, the broad-phase AABB filter that avoids most exact intersection tests, and the handling of the trailer's hitch bar as a special-case line segment.


=== Heading cache <heading_cache>

Rotating a Shapely geometry is expensive: internally, rotation calls `_affine_coords`, which walks every vertex of the polygon through a matrix multiplication. To eliminate this per-query cost, at runtime start the base shapes of each vehicle are pre-rotated to 72 evenly-spaced headings (every $5°$). Per-state footprint queries look up the nearest pre-rotated shape and record only the $(x, y)$ offset, deferring translation until an exact check is actually needed.

#figure(
    image("media/photos/heading_cache.svg", width: 95%),
    caption: [
        *Left:* three of the 72 pre-rotated car footprints stored in the heading cache (shown at 120$degree$ intervals for clarity; the full cache covers every 5$degree$). Arrows indicate the forward direction of each cached shape. *Right:* an example of the worst-case approximation error: the true footprint at 22.5$degree$ versus the nearest cached shape at 20$degree$, the maximum possible snap error being #box[2.5$degree$]. Errors only occur when an obstacle intersects exclusively one discrepancy region (\~3.5% of vehicle area each); obstacles within the shared overlap are correctly detected by both shapes.
    ],
) <fig:heading_cache>

As seen in @fig:collision_opt, this nearly eliminates `rotate` entirely (974,294 calls $->$ 3,622), and drives a #box[65$times$] reduction in `_affine_coords` calls (1,948,445 $->$ 29,917), representing the single largest source of time saved across both optimisations.

=== Broad-phase AABB filter

For rectangular footprints, the translated axis-aligned bounding box (AABB) is simple and cheap to work with. The bounding boxes of the pre-rotated shapes are cached alongside them, so translating to any given state is just an offset addition. No Shapely calls are required.

The bounding box is checked against the environment boundary first: if any part lies outside, the state is immediately rejected without touching any geometry. Otherwise, the AABB is mapped to obstacle grid cell indices and the covered slice is checked for any occupied cell via `_has_possible_collision`. This filter eliminates the majority of exact checks at negligible cost; the full shapely intersection check (`intersects_any`) is only invoked when this phase reports a possible collision.
#figure(
    image("media/photos/aabb_check.svg", width: 100%),
    caption: [
        Broad-phase AABB check for a car footprint (blue) at 35$degree$. The purple obstacle falls inside the AABB but not the footprint: a false positive the exact check resolves. Grey obstacles are skipped entirely.
    ],
) <fig:aabb_check>

The effect is visible in @fig:collision_opt: `_has_possible_collision` appears only in the optimised profile (935,415 calls), while `intersects_any` — the expensive Shapely intersection — drops #box[41$times$] from 938,273 to 23,006 calls. Crucially, `is_valid_state` is called roughly the same number of times in both profiles (487,071 vs 485,689), confirming the AABB filter does not reduce collision accuracy.

The combined effect of these two optimisations is a #box[3.98$times$] end-to-end speedup (81.5 s $->$ 20.5 s). For reference, `propagate` — which handles motion primitive generation and is unaffected by the collision optimisations — shows virtually identical call counts and cost in both profiles, confirming the speedup is attributable entirely to the collision checker.

#figure(
    image("media/photos/collision_opt_comparison.svg", width: 100%),
    caption: [Call counts (*above*) and exclusive CPU time (*below*) for key , comparing the unoptimised and optimised collision checker. Total runtime: 81.5 s (unoptimised) vs 20.5 s (optimised), a #box[3.98$times$] speedup. `propagate` is included as a control to show that primitive generation cost is largely unchanged between runs.]
) <fig:collision_opt>

=== Line segment handling
The trailer's hitch bar connects the truck rear to the trailer's front axle. In this project, this is simplified to a line from the center of the rear axle of the truck to the trailer's front axle. 

This line is stored as raw endpoints rather than a Shapely geometry. Containment within the environment is checked by testing both endpoints against the boundary. Obstacle intersection uses Amanatides and Woo's fast voxel traversal algorithm @10.2312:egtp.19871000 against an occupancy grid, stepping cell-by-cell along the segment and returning on the first occupied cell.

=== Path-level validation
During planning, entire primitive trajectories must be validated, not just individual states. Checking every state exactly would be expensive, but the fine timestep of the simulation justifies skipping most of them: at 5 m/s and 30 fps each step advances the car only 0.167 m — far less than the 5.2 m car length — so consecutive footprints overlap almost entirely (@fig:path_overlap), and a collision missed at an intermediate state is almost certain to also occur at next checked one.

#figure(
    image("media/photos/path_overlap.svg", width: 90%),
    caption: [Car footprints along a 20-step arc. Faint blue shapes are unchecked states; orange outlines mark every 4th state that is actually checked. The 0.67 m spacing between checks is small relative to the 5.2 m car body, so the footprints at checked states subsume those in between.]
) <fig:path_overlap>

A two-phase approach is used. The first pass checks the last state and every 4th intermediate state using the approximate cached footprints — no translation required, just a lookup. This catches virtually all invalid primitives at low cost. If it passes, an optional second phase checks the remaining states with exact translated footprints. This is skipped for most planning iterations and reserved for the final accepted path, where correctness matters more than speed.






== Planner Implementation
=== Hybrid A\*

The planner uses Hybrid A\*, a variant of A\* that operates over a continuous state space rather than a discrete grid. States are represented as continuous $(x, y, theta)$ (plus $phi$ with a trailer); adjacent nodes are generated by sampling a set of control inputs and integrating the vehicle's kinematics forward from the current state, producing one candidate trajectory per input. To prevent the search from cycling through very similar states, duplicate detection is achieved via a discretized grid. XY are positions rounded to the nearest spacing multiple, and headings are floor-divided into angular bins of `angular_spacing` size. Underneath, the node stil contains the continuous state.

#figure(
    image("media/photos/grid_spacing.svg", width: 90%),
    caption: [The 1 m $times$ 1 m duplicate-detection grid overlaid on the car footprint.]
) <fig:grid_spacing>

To ensure the path reaches the exact goal state, a last shot connection is regularly attempted once within range of the goal. While not strictly required, this project applies postprocessing to the final path for smoothness in curvature and velocity.

The heuristic used is the Reeds-Shepp path length @reedsshepp from the current state to the goal, ignoring obstacles. This is admissible and generally tighter than Euclidean distance for non-holonomic robots, as it accounts for turning radius constraints that Euclidean distance ignores @kurzer_path_2016[Section 8.1] @dolgov[Page 2].



#let astar_block = code-block()[
```
function HYBRID_ASTAR(start, goal):
    push start onto open heap
    while open heap is not empty:
        node ← pop lowest f = g + h node
        if node already visited: continue
        mark node visited
        if node is within terminal range of goal:
            path ← LAST_SHOT_CONNECTION(node, goal)
            if path is valid and collision-free:
                return POSTPROCESS(path)
        for each primitive in PROPAGATE(node.state):
            if primitive is collision-free:
                push endpoint onto heap with updated g cost
    return failure
```
]


#figure(astar_block, caption: [Hybrid A\* pseudocode])

The following subsections detail each of these three routines in turn.

=== Primitive Propagation
#figure(
    image("media/photos/primitives_fig.svg", width: 100%),
    caption: [Motion primitives generated from a single car state (heading 30 $degree$). Blue arcs are forward; orange are reverse. *Left:* all 10 primitives — five steering angles ( -45 $degree$, -22.5 $degree$, 0 $degree$, 22.5 $degree$, 45 $degree$ ) $times$ forward/reverse. *Right:* straight primitives ($delta$ = 0) only, shown at the same scale to illustrate their short length relative to the car body — each arc extends only until its endpoint lands in a new grid cell.]
)
At each node, the vehicle generates a set of motion primitives by propagating sampled control inputs. For car-like and trailer vehicles, this means sampling steering angles $delta$ evenly between $-delta_max$ and $+delta_max$, combined with forward and reverse speed. For differential drives, different angular velocities $omega$ are sampled instead. 

Each combination is integrated forward for $n$ timesteps (chosen so the primitive exits its current grid cell — see below). Since $nu$ and $omega$ are constant over each primitive, each trajectory is a circular arc, which allows a closed-form solution rather than requiring iterative integration.#footnote[For derivation, see #ref(<arc_derivation>, supplement: [])]:

$
 
x(i) &= x_0 + R dot (sin(theta (i)) - sin(theta_0)) \
y(i) &= y_0 - R dot (cos(theta (i)) - cos(theta_0)) \
theta (i) &= theta_0 + omega dot i dot d t
$ <eq:arc_trajectory_formula>

where $R = nu / omega$ and $i$ is the $i$-th timestep. Each primitive therefore traces a circular arc. Although Ackermann and differential drive vehicles differ in how $omega$ is derived from their controls, both reduce to the same unicycle model @lav2006[Section 13.1.2.3], so the same formula applies to both.

The step count $n$ is chosen as $max(n_nu, n_omega)$, where each term is the minimum number of steps needed to guarantee the primitive exits its current cell or heading bin:                                                                                                                                                                                                
$ n_nu = ceil(frac("spacing", |nu| dot d t)), quad n_omega = ceil(frac("angular_spacing", |omega| dot d t)) $                                                                                                                                                                                                                                                                    
This ensures every primitive lands in a distinct $(x,y)$ cell and heading bin.

The cost of each primitive (and therefore edge in the A\* graph) is the arc length of the primitive plus a weighted heading change, and an additive penalty for reversals to discourage the planner from exploring backwards.


Two vehicle-specific exceptions apply:
- The differential drive appends additional rotate-in-place primitives with $v = 0$. These primitives have zero arc length, their cost relying purely on heading change, allowing the planner to reason about in-place rotation as a distinct maneuver.

- The trailer's primitive generation is more involved. The truck follows the same analytic arc as any other Ackermann vehicle, but the trailer heading $phi$ is coupled to the truck via a nonlinear ODE:

  $ dot(phi) = frac(v, M) sin(theta - phi) $


  where $M$ is the hitch-to-trailer-axle distance @lav2006[Equation 13.19]. This cannot be integrated in closed form alongside the truck arc, so $phi$ is propagated sequentially: the truck positions and headings are computed analytically in one pass, then $phi$ is stepped forward through the resulting sequence using Euler's method.

  Paths that result in the trailer jackknifing #footnote()[When a vehicle towing a trailer loses control, causing the trailer to swing out and form an acute angle with the towing vehicle, resembling a folding pocket knife.] are treated as invalid: each step is checked against a jackknife limit via the condition $|theta - phi| < 90 degree$. If the limit is exceeded, the primitive is discarded.

=== Last-Shot Connection

When a node falls within a Euclidean distance of `terminal_radius` of the goal pose, an obstacle-free closed-form trajectory is attempted directly to the goal rather than continuing to expand primitives. For car and trailer vehicles this is a Reeds-Shepp path @reedsshepp; for the differential drive it is a rotate-drive-rotate sequence. This avoids the difficulty of landing exactly on the goal pose through discrete primitives, and is the mechanism by which the planner achieves precise heading alignment at the goal.

The connection is not attempted on every node within the terminal radius — since each attempt requires a full collision check, it is only worth trying close to the goal where a direct path is more likely to be clear. Following @kurzer_path_2016[Section 6.1.2], a distance-proportional probability gate is applied, scaling linearly from 0 at the edge of the terminal radius to 1 at the goal:

$ P = 1 - norm(bold(p) - bold(p)_g) / R_t $

where $bold(p) = (x, y)$ is the current position, $bold(p)_g$ is the goal position, and $R_t$ is the terminal radius.

For the trailer vehicle, the trailer heading is simultaneously integrated along the RS path. The connection is rejected if the trailer heading at the goal falls outside a set tolerance, or if jackknifing occurs at any point along it.


=== Post-Processing

The raw path from the search is passed through two steps before playback:

- *Path smoothing* @geraerts_creating_2007[Section 3.2] (`smooth_path`): two random indices are chosen, a direct connection is attempted via `generate_trajectory`, and if collision-free it replaces the span between those two indices. After repeating for 100 iterations, this step reduces total path length by replacing indirect routes imposed by the search order with more direct connections.

#figure(
    grid(
        columns: 2,
        gutter: 1em,
        image("media/photos/path_smoothing_fig_unsmoothed.png"),
        image("media/photos/path_smoothing_fig_smoothed.png"),
    ),
    caption: [Car path before (*left*) and after (*right*) probabilistic shortcutting. The raw path takes a wide detour imposed by the order in which the search explored the space; smoothing finds direct Reeds-Shepp shortcuts that reduce total path length.]
)

- *Resampling* (`resample_path`): the variable-density path is converted to uniform arc-length samples so the animation plays back at constant velocity. Pure-rotation segments (zero XY displacement) are detected separately and resampled at a distinct angular rate.

= Results <results>

#figure(
    grid(
        columns: 2,
        gutter: 1em,
        image("media/photos/bot_nav_photos/point_nav.png"),
        image("media/photos/bot_nav_photos/diff_nav.png"),
        image("media/photos/bot_nav_photos/car_nav.png"),
        image("media/photos/bot_nav_photos/trailer_nav.png"),
    ),
    caption: [Navigation results for each vehicle type: point robot (*top left*), differential drive (*top right*), Ackermann car (*bottom left*), trailer (*bottom right*).]
)

The planner works well across all four vehicle types. The differential drive and car typically find paths within a couple of seconds. The trailer is slower due to its higher-dimensional state space and additional per-step calculations, and its success rate is not 100%: some obstacle layouts produce no reachable path given the jackknife constraints. Failed runs do exhaust the iteration budget quickly though, finishing in around 10 seconds, so the cost of a miss is low. When it does succeed, the trailer produces some satisfying paths: watching it navigate tight spaces and control the heading while reversing is a good demonstration that the coupled kinematics are being handled correctly.

#let bench = csv("data/benchmark.csv", row-type: dictionary)

#let rows-for(bot) = bench.filter(r => r.bot_type == bot)
#let successes(bot) = rows-for(bot).filter(r => r.success == "1")
#let avg(vals) = vals.fold(0.0, (a, b) => a + b) / vals.len()

#let fmt-row(label, dims, bot) = {
  let s = successes(bot)
  let n = rows-for(bot).len()
  let rate = str(s.len()) + "/" + str(n)
  let t = if s.len() > 0 { str(calc.round(avg(s.map(r => float(r.time_s))), digits: 1)) + " s" } else { "—" }
  let exp = if s.len() > 0 { str(int(avg(s.map(r => float(r.expansions))))) } else { "—" }
  (label, dims, rate, t, exp)
}

#figure(
  table(
    columns: 5,
    stroke: none,
    inset: (x: 0.6em, y: 0.45em),
    table.header(
      [*Vehicle*], [*State dims*], [*Success*], [*Avg time*], [*Avg expansions*]
    ),
    table.hline(),
    ..fmt-row([Differential drive], [$x, y, theta$], "diff"),
    ..fmt-row([Ackermann car],       [$x, y, theta$], "car"),
    ..fmt-row([Trailer],             [$x, y, theta, phi$], "trailer"),
  ),
  caption: [Planning performance over 10 runs per vehicle type at 10% obstacle density. Success rate, average planning time, and average node expansions are computed over successful runs only. Planner settings: `spacing=1 m`, `angular_spacing=`$pi\/3$, `max_iterations=45000`, `fine_collision=False`.]
)


The codebase also ended up in a good state structurally; having a clean interface between vehicle types made it easy to experiment with planner parameters and add features without things breaking unexpectedly.

// == Areas for Improvement

// - *Obstacle-aware heuristic.* Augmenting the Reeds-Shepp heuristic with a precomputed Dijkstra cost-to-go map would give tighter estimates and reduce node expansions in cluttered environments @dolgov @kurzer_path_2016.

// - *Inner-loop performance.* Typed dataclass state objects keep the logic readable but carry overhead in the planner's hot path. Switching to raw NumPy arrays (or a zero-copy library like `msgspec`) would speed up both state construction and heuristic computation.

// - *Pure-NumPy collision.* Shapely is still used for narrow-phase checks. Replacing it with SAT-based NumPy intersection tests would remove the external geometry dependency and likely be faster.

// - *Planner visualisation.* Real-time rendering of expanded nodes and the open set would make tuning and debugging much more intuitive; the current sim only shows the final path.

// - *Dynamics and sensing.* Adding a tracking controller, actuator dynamics, or a sensor model would make the simulation more realistic and open up exploration of sensor-based planning.

#pagebreak()


#bibliography("refs.bib", style: "ieee")

#begin-appendices()

#appendix()[
    = Setup <appendix:setup>

    == Installation

    The project requires Python 3.12 and uses #link("https://docs.astral.sh/uv/")[uv] for dependency management. The `reeds_shepp` dependency is vendored under `deps/pyReedsShepp` and built automatically on install.

    ```sh
    git clone <repo-url>
    cd valet

    # create a virtual environment and install all dependencies
    uv sync
    ```

    In addition to the dependencies installed by `uv`, `deps/pyReedsShepp` has an additional C dependency through #link("https://www.boost.org/")[`boost`]. See `README.md` for additional installation instructions.

    == Usage

    Run the simulator with:

    ```sh
    uv run runsim [bot_type] [options]
    ```

    `bot_type` is one of `point`, `diff`, `car`, `trailer` (default: `diff`).

    #table(
        columns: (auto, 1fr),
        stroke: none,
        inset: (x: 0.5em, y: 0.4em),
        table.header([*Flag*], [*Effect*]),
        table.hline(),
        [`-m` / `--manual`], [Drive the bot manually with the keyboard instead of running the planner.],
        [`-r` / `--record`], [Record the simulation to `recording.mp4`.],
        [`-s SEED` / `--seed SEED`], [Fix the RNG seed for reproducible obstacle layouts.],
    )

    Example — run the trailer bot with a fixed seed and record the output:

    ```sh
    uv run runsim trailer -s 12345 -r
    ```
]

#appendix()[
    = Dependencies <appendix:deps>

    - *#link("https://www.pygame.org/")[Pygame]* — provides the real-time 2-D rendering window, keyboard event handling for manual drive mode, and the simulation loop.

    - *#link("https://shapely.readthedocs.io/en/stable/")[Shapely]* — computational geometry library used to represent robot footprints as polygons and query them against obstacle geometry via an STRtree spatial index.

    - *#link("https://imageio.readthedocs.io/")[imageio] / imageio-ffmpeg* — used together to encode simulation recordings to MP4 when the `--record` flag is passed; imageio-ffmpeg supplies the FFmpeg backend.

    - *reeds_shepp (pyReedsShepp)* @liespace_pyreedsshepp — Python bindings to a C++ implementation of Reeds-Shepp path length and curve computations. The original library #cite(<ghliu_pyreedsshepp>) targets an older Python version; a personal fork (vendored at `deps/pyReedsShepp`) was created to update the Cython build configuration for compatibility with the Python version used for the project.
]

#appendix()[
    = Car Goal Offset <appendix:car-offset>

    The Ackermann car goal is specified as a grid-cell offset from the bottom-right corner of the map: `(col_offset=3.575, row_offset=1.425)`. After the standard `+0.5` cell-centering applied by `grid_to_coords`, the true world-coordinate distance from the bottom edge is $0.925$ cell-widths. This non-round value was arrived at by binary search on the row offset.

    The design intent is for the car to perform a parallel parking maneuver: approaching the bottom wall, reversing into the space, and coming to rest with its rear axle close to the wall. The offset must be large enough that the goal pose is reachable via a valid Reeds-Shepp path from the planner's terminal region, but not so large that the car parks away from the wall and the maneuver is lost.


#figure(
    grid(
        columns: 2,
        gutter: 1em,
        grid.cell(colspan: 2, align: center, image("media/photos/car_offset_tuning/1_38-offset-fail-30004.png", width: 50%)),
        image("media/photos/car_offset_tuning/1_39-offset-pass-5719.png"),
         image("media/photos/car_offset_tuning/1_44-offset-pass-2436-noparallel.png")
    ),
    caption: [Offset 1.38 (*above*) exhausts the search after 30,004 expansions without finding a path. Offset 1.39 (*left*) succeeds in 5,719 expansions, confirming the feasibility cutoff. At offset 1.44 (*right*) the car reaches the goal in 2,436 expansions without a parallel parking maneuver, establishing the upper bound of the target window.]
)

// #figure(
//     image("media/photos/car_offset_tuning/1_44-offset-pass-2436-noparallel.png", width: 80%),
//     caption: []
// )

    The final value of 1.425 sits just above the minimum viable offset (1.39), keeping the car goal close to the wall while still allowing the planner to reliably find a path.
]




#appendix()[
    = Derivation of @eq:arc_trajectory_formula <arc_derivation>

    Both the differential drive and Ackermann kinematics can be simplified to the unicycle kinematic model @lav2006[Section 13.1.2.3]:

    $ dot(x) &= nu dot cos(theta) \  dot(y) &= nu dot sin(theta)  \ dot(theta)  &= omega $ <unicycle>

    The differential drive model is directly equivalent, while Ackermann steering has a dependency between the velocity $nu$ and steering angle $delta$:

    $ omega = nu dot tan(delta) / L $ <eq:ackermann_omega>

    where $L$ is the wheelbase (distance between front and rear axles).

   When $nu$ and $omega$ are held constant, the heading evolves linearly as $ theta(t)= theta_0 + omega dot t $, reducing the position integrals to standard trigonometric forms with known closed-form solutions.

    Treating this as an initial value problem with state $(x_0, y_0, theta_0)$ at $t = 0$, the heading integrates directly, as seen above:

    $ theta(t)= theta_0 + omega dot t  $

    Substituting into the position equations and integrating:

    $

    x(t) &= x_0 + integral_0^t nu dot cos(theta_0 + omega dot tau) space d tau = x_0 + lr(frac(nu, omega) dot sin(theta_0 + omega dot tau) |)_(tau=0)^(tau=t) \

    y(t) &= y_0 + integral_0^t nu dot sin(theta_0 + omega dot tau) space d tau = y_0 - lr(frac(nu, omega) dot cos(theta_0 + omega dot tau) |)_(tau=0)^(tau=t)

    $

    Evaluating the bounds and collecting terms gives the integrated trajectory in terms of $nu$ and $omega$: 

    $
    vec(
        x(t) & = x_0 + nu/omega dot (sin(theta(t)) - sin(theta_0)) , 
        y(t) & = y_0 - nu/omega dot (cos(theta(t)) - cos(theta_0)), 
        delim: "[", gap: #1em)
    $
    
    An equivalent form parameterised by the signed turning radius $R = nu / omega$. The Reeds-Shepp library takes turning radius as an input, so the codebase reasons in terms of $R$ throughout:

    To justify $R$ as the turning radius: for any body undergoing circular motion of radius $R$ at angular rate $omega$, the tangential speed is $nu = omega R$ @wiki_tangential_speed, so $R = nu / omega$ by definition. The two vehicle types differ in how $R$ is constrained:

    - *Differential drive*: $nu$ and $omega$ are set independently via wheel speeds, so $R$ can take any value. This includes $R = 0$ (spin in place, $nu = 0$) and $R = infinity$ (straight line, $omega = 0$). There is no minimum turning radius.

    - *Ackermann*: the steering geometry fixes $R = L / tan(delta)$ @lav2006[Section 13.1.2.1], and from @eq:ackermann_omega, $omega = nu dot tan(delta) \/ L$, so $nu / omega = L / tan(delta) = R$. But now $R$ is bounded below: at $delta = delta_"max"$, $R$ reaches its minimum $R_"min" = L / tan(delta_"max")$.

    In both cases the arc formula is the same; only the domain of valid $R$ differs. Substituting $R = nu / omega$:

    $
    vec(x(t) & = x_0 + R dot (sin(theta(t)) - sin(theta_0)) , y(t) & = y_0 - R dot (cos(theta(t)) - cos(theta_0)), delim: "[", gap: #1em)
    $

    This can be extended to include the case of $omega approx 0 => R = v / 0$, where the arc approaches a straight line as $R -> infinity$. Since the heading is constant, the velocity components are fixed, and the kinematics follow directly from @unicycle:
    $
      vec(
        x(t)        & = x_0 + dot(x) dot t = x_0 + nu  dot cos(theta_0) dot t, 
        y(t)        & = y_0 + dot(y) dot t = y_0 + nu  dot sin(theta_0) dot t, 
        theta(t)    & = theta_0 + omega dot t = theta_0, 
      
      delim: "[", gap: #1em)
    $ <eq:straight_line>

    This result can be verified formally via L'Hôpital's rule applied to the arc equations as $omega -> 0$:
    $
      lim_(omega->0) (nu dot (sin(theta_0 + omega dot t) - sin(theta_0))) / omega = 0 / 0 = lim_(omega->0) (nu dot cos(theta_0  + 0 dot t) dot t - 0) / 1 = nu  dot cos(theta_0)dot t
    $

    $
        lim_(omega->0) (nu dot (cos(theta_0 + omega dot t) - cos(theta_0))) / omega = 0 / 0 = lim_(omega->0) (nu dot -sin(theta_0 + 0 dot t) dot t - 0) / 1 = -nu  dot sin(theta_0) dot t
    $

    which recovers the straight-line equations. The $omega -> 0$ branch is the only degenerate case that requires special handling: stationary rotation ($nu = 0, abs(omega) > 0$) is well-defined everywhere, and an Ackermann vehicle cannot physically produce $nu = 0, omega != 0$ anyway, since that would require $delta = 90 degree$ and $tan(delta) -> infinity$ (@eq:ackermann_omega).

    Together, these two cases — circular arc (@eq:arc_trajectory_formula) and straight line — form a complete closed-form solution for the truck (and differential drive) portion of all primitives, each evaluable for all $n$ timesteps in a single vectorised pass. 
    
    The trailer heading $phi$ is the exception: its coupling ODE is likely analytically solvable, but deriving the full solution was considered outside the scope of this project. Euler integration over the pre-computed truck states is simpler and acceptably correct (covered in the main body).
]



